// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package person

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientStreamClient is the client API for ClientStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientStreamClient interface {
	GetPersonClientStream(ctx context.Context, opts ...grpc.CallOption) (ClientStream_GetPersonClientStreamClient, error)
}

type clientStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewClientStreamClient(cc grpc.ClientConnInterface) ClientStreamClient {
	return &clientStreamClient{cc}
}

func (c *clientStreamClient) GetPersonClientStream(ctx context.Context, opts ...grpc.CallOption) (ClientStream_GetPersonClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ClientStream_ServiceDesc.Streams[0], "/code.ClientStream/GetPersonClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientStreamGetPersonClientStreamClient{stream}
	return x, nil
}

type ClientStream_GetPersonClientStreamClient interface {
	Send(*Ids) error
	CloseAndRecv() (*Person, error)
	grpc.ClientStream
}

type clientStreamGetPersonClientStreamClient struct {
	grpc.ClientStream
}

func (x *clientStreamGetPersonClientStreamClient) Send(m *Ids) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientStreamGetPersonClientStreamClient) CloseAndRecv() (*Person, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Person)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientStreamServer is the server API for ClientStream service.
// All implementations must embed UnimplementedClientStreamServer
// for forward compatibility
type ClientStreamServer interface {
	GetPersonClientStream(ClientStream_GetPersonClientStreamServer) error
	mustEmbedUnimplementedClientStreamServer()
}

// UnimplementedClientStreamServer must be embedded to have forward compatible implementations.
type UnimplementedClientStreamServer struct {
}

func (UnimplementedClientStreamServer) GetPersonClientStream(ClientStream_GetPersonClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPersonClientStream not implemented")
}
func (UnimplementedClientStreamServer) mustEmbedUnimplementedClientStreamServer() {}

// UnsafeClientStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientStreamServer will
// result in compilation errors.
type UnsafeClientStreamServer interface {
	mustEmbedUnimplementedClientStreamServer()
}

func RegisterClientStreamServer(s grpc.ServiceRegistrar, srv ClientStreamServer) {
	s.RegisterService(&ClientStream_ServiceDesc, srv)
}

func _ClientStream_GetPersonClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientStreamServer).GetPersonClientStream(&clientStreamGetPersonClientStreamServer{stream})
}

type ClientStream_GetPersonClientStreamServer interface {
	SendAndClose(*Person) error
	Recv() (*Ids, error)
	grpc.ServerStream
}

type clientStreamGetPersonClientStreamServer struct {
	grpc.ServerStream
}

func (x *clientStreamGetPersonClientStreamServer) SendAndClose(m *Person) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientStreamGetPersonClientStreamServer) Recv() (*Ids, error) {
	m := new(Ids)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ClientStream_ServiceDesc is the grpc.ServiceDesc for ClientStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "code.ClientStream",
	HandlerType: (*ClientStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPersonClientStream",
			Handler:       _ClientStream_GetPersonClientStream_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "code/client_stream.proto",
}
